# Generated by Django 5.2.14 on 2026-05-31 19:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FeedSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('url', models.URLField(unique=True, verbose_name='RSS URL')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('last_fetched_at', models.DateTimeField(blank=True, null=True, verbose_name='Последнее обновление')),
            ],
            options={
                'verbose_name': 'Источник',
                'verbose_name_plural': 'Источники',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, verbose_name='Заголовок')),
                ('link', models.URLField(unique=True, verbose_name='Ссылка')),
                ('summary', models.TextField(blank=True, verbose_name='Краткое описание')),
                ('published_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Дата публикации')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Добавлено')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='news.feedsource', verbose_name='Источник')),
            ],
            options={
                'verbose_name': 'Статья',
                'verbose_name_plural': 'Статьи',
                'ordering': ['-published_at', '-created_at'],
            },
        ),
    ]
